name: content-init-build

# This workflow is triggered on push to the 'content-web' directory of the  master branch of the repository
on:
  push:
    branches:
    - master
    paths:
    - 'content-init/**'

  # Configure workflow to also support triggering manually
  workflow_dispatch:



# Jobs define the actions that take place when code is pushed to the master branch
jobs:

  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@master

    - name: Build and push an image to container registry
      run: |
        npm install 
      
       
